### ISSUE TITLE
Make the Upload Book page

### ISSUE THREAD

**Issue by nihal111** [Ferozepurwale/LendIt-App#4]
![image uploaded from ios](https://user-images.githubusercontent.com/13916513/29772021-5877883c-8c14-11e7-81b0-5724856521a6.jpg)

There should be an upload button on the home screen.
Clicking the upload button takes you to a new screen called InitiateUploadActivity, that looks like this-

![screenshot_2017-08-28-17-16-11-497_net one97 paytm](https://user-images.githubusercontent.com/13916513/29772390-37ad4644-8c16-11e7-9c1d-00c9be69ab4d.png)

The top field should be- "Enter Name of the Book". Clicking on this should open a new page similar to PayTM, with fields like "Name of the Book", "Condition" etc present. Let's call this page FinalUploadActivity. Fields like "ISBN Code" would be hidden if entering into FinalUploadActivity through this process. Cursor should automatically be on the Name field. There needs to be an auto complete feature here, but that can be dealt with in a separate issue.

![screenshot_2017-08-28-17-18-28-199_net one97 paytm](https://user-images.githubusercontent.com/13916513/29772395-3b498768-8c16-11e7-8d86-14fdc15f080f.png)

The Scanner should have a label saying "Point at ISBN barcode to scan". Integrate an ISBN bar code scanner here. Can be done as a part of another issue. Should ultimately take you to the FinalUploadActivity with some fields filled.

The option at the bottom should read "Enter ISBN Code manually", should take you to FinalUploadActivity again with the cursor on ISBN code. Fields like Name, Author etc would be filled automatically when the ISBN code is recognized.

**Comment by nihal111** [comment]
Pinging @arpan98 and @CodeMaxx for more comments.

**Comment by CodeMaxx** [comment]
Looks good to me; @TheFlash98 @ydidwania One of you should word on the scanning thing(and getting there on pressing upload button) and other should work on the ISBN recognition and data fetching thing.

**Comment by arpan98** [comment]
Closing in favour of follow up issue #7
